### ISSUE TITLE
Major improvements

### ISSUE THREAD

**Issue by 93v** [93v/dynatron#13]
**Is your feature request related to a problem? Please describe.**
The current version of Dynatron has some shortcomings that could be improved
- The need to init the Dynatron (although internally there is some singleton magic)
- The limited capabilities to provide a request handler
- Because of always creating an internal request handler for node, the lib doesn't work in browsers or `cloudflare`

**Describe the solution you'd like**
1. Table name should not be passed to the constructor, instead use a .tableName or .table function
2. Dynatron should receive a DynamoDBClient on init as new DynatronClient
3. DynatronClient can receive an option client configuration
4. DynatronClient can receive an optional `requestHandler`
5. Move the NodeHttpHandler custom code into an OptimizedNodeRequestHandler class

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

This should ultimately become a new major release version, so please follow the commit naming to support semantic versioning

**Comment by Arattian** [comment]
https://github.com/93v/dynatron/pull/16

**Comment by 93v** [comment]
Done with https://github.com/93v/dynatron/pull/21
