### ISSUE TITLE
Batch Result type restrictions

### ISSUE THREAD

**Issue by Arattian** [93v/dynatron#36]
**Is your feature request related to a problem? Please describe.**
If we pass for example `TypeName[]` else by mistake, it will overwrite the default type and typescript will not complain about it. But the return value will still be in a Record<string, any[]> format.

**Describe the solution you'd like**
It would be awesome if Batch methods would require the passed type to be in a Record<string, TypeName[]> format,

**Describe alternatives you've considered**
Or, have a wrapper type like this one.

```
export type BatchResult<T> = {
  [key: string]: T;
};
```

**Comment by gevorggalstyan** [comment]
Being resolved with https://github.com/93v/dynatron/pull/38
