### ISSUE TITLE
Please do not throw an error if update body contains hash or range key of an element. 

### ISSUE THREAD

**Issue by Arattian** [93v/dynatron#8]
**Is your feature request related to a problem? Please describe.**
During development, we often do not know what properties does update body has and what doesn't, which often causes a DynamoDb error like "Can not update hash key of an element" even if the hash key in the body matches with the key in the table. 

The workaround for this often looks like this. 

```
  const { id, ...rest } = ctx.request.body;
  await db(USERS_TABLE)
    .update({ id: id || ctx.params.id })
    .assign(rest)
    .returnValues("ALL_NEW")
    .$();
```

**Describe the solution you'd like**
Filter out the hash and range key from an "assign" object during the update process.

**Comment by Arattian** [comment]
https://github.com/93v/dynatron/pull/10

**Comment by gevorggalstyan** [comment]
Has been added to the version 5.
